#!/usr/bin/env python3
"""
test_bundle.py -- Pre-flight validation for Supero generated apps.

Validates app generation quality WITHOUT running ./run.sh or starting
the server. Zero external dependencies -- uses only Python stdlib.

Checks:
  1. Required files    -- all expected files exist and aren't empty/truncated
  2. .env config       -- required vars, auth, project name, port consistency
  3. Schema validation -- syntax, namespaces, enum refs, reference targets
  4. Config validation -- app_name, tenants, users, roles, env wiring
  5. Setup.py          -- syntax, required functions, seed field name accuracy
  6. config.js         -- domain, project, appNamespace, public schemas
  7. app.js            -- AppShell, render(), SUPERO_CONFIG wiring, tabs
  8. supero-ui.js      -- _qualifySchema, SuperoClient, size check
  9. run.sh            -- SDK version stamped, executable
 10. Dockerfile        -- FROM, COPY, CMD, no .env leak
 11. Documentation     -- README.md, CLAUDE.md, CUSTOMIZATION.md
 12. Public wiring     -- .env -> config.js -> app.js end-to-end
 13. Seed field match  -- seed_record field names vs schema attributes
 14. SDK versions      -- base SDK installed, version matches run.sh pin
 15. Post-install      -- API key, config.js project, backend records

Ships with the app bundle (generated by AI service).
Run BEFORE ./run.sh to catch generation errors early.
Run AFTER ./run.sh to validate post-install state.

Usage:
    python3 test_bundle.py                # full pre-flight validation
    python3 test_bundle.py --bail         # stop on first failure
    python3 test_bundle.py --json         # JSON output for CI
    python3 test_bundle.py --post-install # include backend record checks
"""

import os
import sys
import re
import ast
import time
import json
import argparse
from dataclasses import dataclass, field
from typing import List

# ---------------------------------------------------------------
# Load app config and schemas
# ---------------------------------------------------------------

# TESTS_FOLDER_V1 — test_bundle.py lives in tests/, so go up one more level
APP_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, APP_DIR)

try:
    from schemas import ALL_SCHEMAS
except ImportError:
    print("  \033[31m\u2717\033[0m Cannot import schemas.py -- run from the app directory")
    sys.exit(1)
except SyntaxError as e:
    print(f"  \033[31m\u2717\033[0m schemas.py has SYNTAX ERROR: {e}")
    print(f"    File may be truncated by LLM token limit. Check line {e.lineno}.")
    sys.exit(1)
try:
    from schemas import SUPERO_APP_NAMESPACE  # legacy bundles only
except Exception:
    # ABSOLUTE-NAMESPACE-FROM-CONTENT-V1 \u2014 modern bundles carry NO
    # SUPERO_APP_NAMESPACE variable; derive the primary namespace from ALL_SCHEMAS.
    _ns_counts = {}
    for _s in ALL_SCHEMAS:
        if isinstance(_s, dict) and str(_s.get("namespace", "")).strip():
            _n = str(_s["namespace"]).strip().lower().replace("-", "_")
            _ns_counts[_n] = _ns_counts.get(_n, 0) + 1
    SUPERO_APP_NAMESPACE = (sorted(_ns_counts, key=lambda n: (-_ns_counts[n], n))[0]
                            if _ns_counts else "")

try:
    from config import AppConfig
except ImportError:
    print("  \033[31m\u2717\033[0m Cannot import config.py -- run from the app directory")
    sys.exit(1)
except SyntaxError as e:
    print(f"  \033[31m\u2717\033[0m config.py has SYNTAX ERROR: {e}")
    print(f"    File may be truncated by LLM token limit. Check line {e.lineno}.")
    sys.exit(1)

# ---------------------------------------------------------------
# .env loader (stdlib only -- no dotenv dependency)
# ---------------------------------------------------------------

def _load_env(env_path):
    if not os.path.exists(env_path):
        return
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))

_load_env(os.path.join(APP_DIR, ".env"))

def _env(key, default=""):
    return os.getenv(key, default)

DOMAIN = _env("SUPERO_DOMAIN")
PROJECT = _env("SUPERO_PROJECT", "default-project")
API_KEY = _env("SUPERO_API_KEY")
ADMIN_EMAIL = _env("SUPERO_ADMIN_EMAIL")
ADMIN_PASS = _env("SUPERO_PASSWORD")
IS_MULTI_TENANT = _env("SUPERO_IS_MULTI_TENANT", "").lower() == "true"
HAS_VENV = os.path.exists(os.path.join(APP_DIR, ".venv"))
PUBLIC_SCHEMAS_STR = _env("PUBLIC_SCHEMAS")
PUBLIC_SCHEMAS = [s.strip() for s in PUBLIC_SCHEMAS_STR.split(",") if s.strip()]

cfg = AppConfig()

# ---------------------------------------------------------------
# Schema helpers
# ---------------------------------------------------------------

# SNAKE-ACRONYM-FOLD-V1 — canonical schema_naming normalizer (PackageFAQ ->
# package_faq, not package_f_a_q); regex fallback when the SDK is absent.
try:
    from supero.schema_naming import normalize_schema_name as _to_snake
except ImportError:
    def _to_snake(name):
        s = re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', name)
        return re.sub(r'(?<=[A-Z])(?=[A-Z][a-z])', '_', s).lower()

OBJECT_SCHEMAS = [s for s in ALL_SCHEMAS if s.get("schema_type") == "object"]
ENUM_SCHEMAS = [s for s in ALL_SCHEMAS if s.get("schema_type") == "enum"]

ENUM_MAP = {}
for _es in ENUM_SCHEMAS:
    ENUM_MAP[_es["name"]] = _es.get("values", [])
    ENUM_MAP[_to_snake(_es["name"])] = _es.get("values", [])

# ---------------------------------------------------------------
# Test result tracking
# ---------------------------------------------------------------

@dataclass
class TestResult:
    section: str
    name: str
    passed: bool
    skipped: bool = False
    message: str = ""

@dataclass
class TestSuite:
    results: List[TestResult] = field(default_factory=list)
    bail: bool = False
    json_output: bool = False
    _start_time: float = field(default_factory=time.time)

    def ok(self, section, name, msg=""):
        self.results.append(TestResult(section, name, True, False, msg))
        if not self.json_output:
            print(f"    \033[32m\u2713\033[0m {name}")

    def fail(self, section, name, msg=""):
        self.results.append(TestResult(section, name, False, False, msg))
        if not self.json_output:
            print(f"    \033[31m\u2717\033[0m {name}")
            if msg:
                for line in msg.splitlines()[:5]:
                    print(f"      {line}")
        if self.bail:
            self.print_summary()
            sys.exit(1)

    def skip(self, section, name, reason=""):
        self.results.append(TestResult(section, name, True, True, f"SKIPPED: {reason}"))
        if not self.json_output:
            print(f"    \033[33m\u25cb\033[0m {name} (skipped: {reason})")

    def print_summary(self):
        passed = sum(1 for r in self.results if r.passed and not r.skipped)
        failed = sum(1 for r in self.results if not r.passed)
        skipped = sum(1 for r in self.results if r.skipped)
        total = len(self.results)
        elapsed = time.time() - self._start_time

        if self.json_output:
            print(json.dumps({
                "passed": passed, "failed": failed, "skipped": skipped,
                "total": total, "elapsed_s": round(elapsed, 1),
                "tests": [
                    {"section": r.section, "name": r.name, "passed": r.passed,
                     "skipped": r.skipped, "message": r.message}
                    for r in self.results
                ],
            }, indent=2))
            return failed == 0

        # Per-section summary
        sections = {}
        for r in self.results:
            s = sections.setdefault(r.section, {"pass": 0, "fail": 0, "skip": 0})
            if r.skipped:
                s["skip"] += 1
            elif r.passed:
                s["pass"] += 1
            else:
                s["fail"] += 1

        print(f"\n{'='*60}")
        print(f"  Bundle Validation: {passed} passed, {failed} failed, {skipped} skipped ({elapsed:.1f}s)")
        print(f"  Total checks: {total}")
        print()
        for sec, counts in sections.items():
            status = "\033[32m\u2713\033[0m" if counts["fail"] == 0 else "\033[31m\u2717\033[0m"
            print(f"    {status} {sec}: {counts['pass']} passed"
                  + (f", {counts['fail']} failed" if counts["fail"] else "")
                  + (f", {counts['skip']} skipped" if counts["skip"] else ""))
        if failed:
            print(f"\n  Failures:")
            for r in self.results:
                if not r.passed:
                    print(f"    \033[31m\u2717\033[0m [{r.section}] {r.name}")
                    if r.message:
                        print(f"      {r.message[:120]}")
        print(f"{'='*60}")
        return failed == 0


# ===============================================================
# VALIDATION CHECKS
# ===============================================================

def check_required_files(suite):
    if not suite.json_output:
        print("\n  [1] Required Files\n")

    _has_venv = os.path.exists(os.path.join(APP_DIR, ".venv"))

    # Files from AI generation (always expected)
    pre_install = {
        "schemas.py": "Schema definitions",
        "config.py": "App configuration",
        "setup.py": "Setup + seed data",
        "run.sh": "App launcher (bash)",
        "run.bat": "App launcher (Windows)",
        ".env": "Environment config",
        "ui/app.js": "App UI logic",
    }
    # Files created by ./run.sh (only expected after install)
    post_install = {
        "Dockerfile": "Docker build",
        "docker-compose.yml": "Docker Compose",
        "README.md": "Documentation",
        "CLAUDE.md": "AI assistant context",
        "ui/index.html": "Web UI entry",
        "ui/config.js": "Browser config",
        "ui/server.py": "Local proxy",
        "ui/supero-ui.js": "Supero UI framework (legacy monolith — kept for /supero-ui.js route fallback)",
        # LAYERED_UI_V1 — index.html.tmpl now loads these 24 ordered files
        # instead of the monolithic supero-ui.js.
        "ui/web/00-header.js":                       "Supero UI: load guards + config",
        "ui/web/api/10-schemas.js":                  "Supero UI: schema registry",
        "ui/web/api/11-client.js":                   "Supero UI: SuperoClient CRUD",
        "ui/web/api/12-helpers.js":                  "Supero UI: formatters + state machine",
        "ui/web/services/20-map.js":                 "Supero UI: services map",
        "ui/web/services/22-catalog.js":             "Supero UI: ACTION_OPS + SERVICE_MANIFESTS",
        "ui/web/ui-core/30-primitives.js":           "Supero UI: buttons + cards + icons",
        "ui/web/ui-service/40-fields-forms.js":      "Supero UI: form modals + field editors",
        "ui/web/ui-app/53-shell.js":                 "Supero UI: AppShell + Dashboard",
        "ui/web/ui-app/54-nav-widgets.js":           "Supero UI: nav widgets (last file — supero:ready dispatched after)",
    }

    for filepath, desc in pre_install.items():
        full = os.path.join(APP_DIR, filepath)
        if os.path.exists(full):
            size = os.path.getsize(full)
            if size == 0:
                suite.fail("files", f"{filepath} (empty!)", desc)
            elif size < 50 and filepath.endswith(".py"):
                suite.fail("files", f"{filepath} ({size}B -- truncated?)", desc)
            else:
                suite.ok("files", f"{filepath} ({size:,}B)")
        else:
            suite.fail("files", f"{filepath} MISSING", desc)

    for filepath, desc in post_install.items():
        full = os.path.join(APP_DIR, filepath)
        if os.path.exists(full):
            size = os.path.getsize(full)
            if size == 0:
                suite.fail("files", f"{filepath} (empty!)", desc)
            else:
                suite.ok("files", f"{filepath} ({size:,}B)")
        elif _has_venv:
            suite.fail("files", f"{filepath} MISSING (post-install)", desc)
        else:
            suite.skip("files", f"{filepath} not yet created",
                       "Run ./run.sh first")


def check_env(suite):
    if not suite.json_output:
        print("\n  [2] .env Configuration\n")

    env_path = os.path.join(APP_DIR, ".env")
    env_vars = {}
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    k, v = line.split("=", 1)
                    env_vars[k.strip()] = v.strip().strip('"').strip("'")

    # Required vars
    for var, desc in {
        "SUPERO_URL": "Platform API URL",
        "SUPERO_DOMAIN": "Domain name",
        "SUPERO_PROJECT": "Project name",
        "SUPERO_ADMIN_EMAIL": "Admin email",
    }.items():
        val = env_vars.get(var, "")
        if val:
            suite.ok("env", f"{var} = {val[:40]}{'...' if len(val) > 40 else ''}")
        else:
            suite.fail("env", f"{var} NOT SET", desc)

    # Auth
    has_key = bool(env_vars.get("SUPERO_API_KEY", ""))
    has_pass = bool(env_vars.get("SUPERO_PASSWORD", ""))
    if has_key:
        key_val = env_vars["SUPERO_API_KEY"]
        suite.ok("env", f"SUPERO_API_KEY = ...{key_val[-4:]}")
        if key_val.startswith("ak_"):
            parts = key_val.split("_")
            if len(parts) >= 4:
                if parts[1] == env_vars.get("SUPERO_DOMAIN", ""):
                    suite.ok("env", f"API key domain matches: {parts[1]}")
                else:
                    suite.fail("env", "API key domain MISMATCH",
                               f"Key='{parts[1]}' vs DOMAIN='{env_vars.get('SUPERO_DOMAIN', '')}'")
                if parts[2] == env_vars.get("SUPERO_PROJECT", ""):
                    suite.ok("env", f"API key project matches: {parts[2]}")
                else:
                    suite.fail("env", "API key project MISMATCH",
                               f"Key='{parts[2]}' vs PROJECT='{env_vars.get('SUPERO_PROJECT', '')}'")
        else:
            suite.fail("env", "API key format invalid", "Should start with 'ak_'")
    elif has_pass:
        suite.ok("env", "SUPERO_PASSWORD set (will fetch API key on first run)")
    else:
        if HAS_VENV:
            suite.fail("env", "No auth configured", "Need SUPERO_API_KEY or SUPERO_PASSWORD")
        else:
            suite.skip("env", "No auth yet",
                       "API key will be created on first ./run.sh")

    # Project name
    project = env_vars.get("SUPERO_PROJECT", "")
    if project.lower() in ("default-project", "default_project", "default"):
        suite.fail("env", f"SUPERO_PROJECT='{project}' (reserved!)",
                   "Must use a real project name")
    elif project:
        suite.ok("env", f"SUPERO_PROJECT='{project}' (valid)")

    # PORT / UI_PORT consistency
    port = env_vars.get("PORT", "")
    ui_port = env_vars.get("UI_PORT", "")
    if port:
        suite.ok("env", f"PORT={port}")
    if port and ui_port and port != ui_port:
        suite.fail("env", f"PORT={port} != UI_PORT={ui_port}", "Should match")

    # Multi-tenant env
    if env_vars.get("SUPERO_IS_MULTI_TENANT", "").lower() == "true":
        for noun in ["SUPERO_TENANT_NOUN_SINGULAR", "SUPERO_TENANT_NOUN_PLURAL"]:
            val = env_vars.get(noun, "")
            if val:
                suite.ok("env", f"{noun}={val}")
            else:
                suite.skip("env", f"{noun} not set", "Default: Workspace/Workspaces")

    # PROJECT vs PROJECT_DISPLAY
    proj_disp = env_vars.get("SUPERO_PROJECT_DISPLAY", "")
    if proj_disp and project and proj_disp == project:
        suite.skip("env", "PROJECT_DISPLAY == PROJECT",
                   "Display name should differ from slug (slug has suffix)")
    elif proj_disp and project:
        suite.ok("env", f"PROJECT_DISPLAY='{proj_disp}' vs PROJECT='{project}' (distinct)")


def check_schemas(suite):
    if not suite.json_output:
        print("\n  [3] Schema Validation\n")

    if not ALL_SCHEMAS:
        suite.fail("schemas", "ALL_SCHEMAS is empty")
        return

    suite.ok("schemas", f"{len(ALL_SCHEMAS)} schemas "
             f"({len(OBJECT_SCHEMAS)} objects, {len(ENUM_SCHEMAS)} enums)")

    seen_names = set()
    for schema in ALL_SCHEMAS:
        sname = schema.get("name", "")
        stype = schema.get("schema_type", "")
        ns = schema.get("namespace", "")

        if not sname:
            suite.fail("schemas", "Schema with no name", str(schema)[:80])
            continue
        if sname in seen_names:
            suite.fail("schemas", f"Duplicate: {sname}")
        seen_names.add(sname)

        if not ns:
            suite.fail("schemas", f"{sname}: missing namespace")
        elif ns != SUPERO_APP_NAMESPACE and ns not in ("email", "slack", "wf", "sys"):
            suite.fail("schemas", f"{sname}: unexpected namespace '{ns}'")

        if stype == "object":
            attrs = schema.get("attributes", [])
            if not attrs:
                suite.fail("schemas", f"{sname}: no attributes")
            else:
                mandatory = [a["name"] for a in attrs if a.get("mandatory")]
                suite.ok("schemas", f"{sname}: {len(attrs)} attrs, {len(mandatory)} mandatory")

            # Validate references point to existing schemas
            for ref in schema.get("references", []):
                ref_name = ref.get("name", "")
                if ref_name and not any(s["name"] == ref_name for s in ALL_SCHEMAS):
                    suite.fail("schemas", f"{sname} -> {ref_name} (ref target not found!)")
                elif ref_name:
                    suite.ok("schemas", f"{sname} -> {ref_name} (ref valid)")

            # Validate enum type references
            for attr in attrs:
                atype = attr.get("type", "")
                if (atype and atype[0].isupper() and
                    atype not in ("Image", "RichText", "DateTime", "Date",
                                  "Email", "URL", "Phone", "File",
                                  "Address", "ContactInfo", "DateRange",
                                  "GeoLocation", "PhoneNumber", "Currency",
                                  "Signature", "DisplayNameMap",
                                  "AppArtifact")):
                    if not any(s["name"] == atype for s in ENUM_SCHEMAS):
                        suite.fail("schemas",
                                   f"{sname}.{attr['name']}: enum type '{atype}' not found")

        elif stype == "enum":
            values = schema.get("values", [])
            if not values:
                suite.fail("schemas", f"{sname}: enum with no values")
            else:
                suite.ok("schemas", f"{sname}: {len(values)} enum values")


def check_config(suite):
    if not suite.json_output:
        print("\n  [4] Config Validation\n")

    if not cfg.app_name:
        suite.fail("config", "app_name is empty")
    else:
        suite.ok("config", f"app_name: {cfg.app_name}")

    if cfg.app_emoji:
        suite.ok("config", f"app_emoji: {cfg.app_emoji}")
    else:
        suite.skip("config", "app_emoji not set", "Optional")

    if not cfg.tenants:
        suite.fail("config", "No tenants defined")
    else:
        names = [t["name"] for t in cfg.tenants]
        suite.ok("config", f"Tenants: {', '.join(names)}")
        if names == ["default-tenant"]:
            suite.fail("config", "Only default-tenant", "Need at least one custom tenant")

    if not cfg.users:
        suite.fail("config", "No users defined")
    else:
        roles = set(u.get("role", "?") for u in cfg.users)
        suite.ok("config", f"Users: {len(cfg.users)} ({', '.join(roles)})")
        if not roles & {"tenant_admin", "domain_admin"}:
            suite.fail("config", "No admin user defined")

    # project_name should read from env
    config_path = os.path.join(APP_DIR, "config.py")
    if os.path.exists(config_path):
        with open(config_path) as f:
            csrc = f.read()
        if 'os.getenv("SUPERO_PROJECT"' in csrc or "os.getenv('SUPERO_PROJECT'" in csrc:
            suite.ok("config", "project_name reads from SUPERO_PROJECT env")
        else:
            suite.fail("config", "project_name may be hardcoded")


def check_setup_py(suite):
    if not suite.json_output:
        print("\n  [5] Setup.py Validation\n")

    setup_path = os.path.join(APP_DIR, "setup.py")
    if not os.path.exists(setup_path):
        suite.fail("setup", "setup.py not found")
        return

    with open(setup_path) as f:
        setup_src = f.read()

    # Syntax check
    try:
        setup_tree = ast.parse(setup_src)
        suite.ok("setup", "setup.py syntax valid")
    except SyntaxError as e:
        suite.fail("setup", f"setup.py SYNTAX ERROR: {e}",
                   "File may be truncated by LLM token limit")
        return

    # Required functions
    for func in ["seed_test_data", "main"]:
        if f"def {func}" in setup_src:
            suite.ok("setup", f"Function: {func}()")
        else:
            suite.fail("setup", f"Missing function: {func}()")

    # Seed type references match schemas
    seed_calls = re.findall(r'seed_record\([^)]*?["\'](\w+)["\']', setup_src)
    schema_names_lower = {_to_snake(s["name"]) for s in OBJECT_SCHEMAS}
    for seed_type in set(seed_calls):
        if _to_snake(seed_type) in schema_names_lower:
            suite.ok("setup", f"Seed type '{seed_type}' matches schema")
        else:
            suite.fail("setup", f"Seed type '{seed_type}' has no matching schema",
                       f"Known: {', '.join(sorted(schema_names_lower)[:8])}")

    # Workflow definitions
    if "WORKFLOW_DEFINITIONS" in setup_src:
        suite.ok("setup", "WORKFLOW_DEFINITIONS defined")
    else:
        suite.skip("setup", "No WORKFLOW_DEFINITIONS", "App has no workflows")

    # Hardcoded domain
    for hd in re.findall(r'domain\s*=\s*["\']([a-z][a-z0-9-]+)["\']', setup_src):
        if hd not in ("default", "test", "example"):
            suite.fail("setup", f"Hardcoded domain: '{hd}'")

    # Seed record count — count actual seed data calls
    # Pattern 1: seed_record(s, base, domain, "SchemaName", {...})
    # Pattern 2: make_seed_record binding + seed_record(...) calls
    # Pattern 3: s.post(f"{base}/api/v1/crud/{domain}/type", json=...)  — direct CRUD
    # Pattern 4: data arrays like categories = [...], products = [...]
    seed_count = len(re.findall(r'seed_record\s*\(', setup_src))
    binding_count = len(re.findall(r'seed_record\s*=\s*make_seed_record', setup_src))
    actual_seeds = seed_count - binding_count
    # Count direct CRUD POST calls (s.post(...crud...))
    actual_seeds += len(re.findall(r'\.post\s*\(\s*f?["\'].*?crud.*?json\s*=', setup_src))
    # Count other seed patterns
    for pattern in [r'\.create\s*\(', r'\.seed\s*\(', r'create_with_children\s*\(']:
        actual_seeds += len(re.findall(pattern, setup_src))
    # If still 0, count data arrays (categories = [...], products = [...])
    if actual_seeds == 0:
        # Look for list-of-dict patterns: variable = [{...}, {...]
        data_arrays = re.findall(r'^\s{4}(\w+)\s*=\s*\[', setup_src, re.MULTILINE)
        # Filter to likely seed data (not imports, not constants)
        seed_arrays = [a for a in data_arrays
                       if a not in ("WORKFLOW_DEFINITIONS", "sys", "os")
                       and not a.startswith("_") and not a.isupper()]
        actual_seeds = len(seed_arrays)
    schema_count = len(OBJECT_SCHEMAS)
    if actual_seeds == 0:
        suite.fail("setup", "No seed data found", "App starts with empty data")
    elif actual_seeds < schema_count:
        suite.skip("setup",
                   f"{actual_seeds} seed sources for {schema_count} schemas",
                   "Some schemas may not have test data (OK if seeded via references)")
    else:
        suite.ok("setup", f"{actual_seeds} seed sources for {schema_count} schemas")

    # Public schemas have seed data
    for ps in PUBLIC_SCHEMAS:
        if not ps:
            continue
        ps_snake = _to_snake(ps) if ps[0].isupper() else ps
        if ps_snake in setup_src or ps in setup_src:
            suite.ok("setup", f"Public schema '{ps}' has seed data")
        else:
            suite.fail("setup", f"Public schema '{ps}' has NO seed data",
                       "Landing page will be empty")

    # ── Seed field names vs schema attributes ──
    if not suite.json_output:
        print("\n  [6] Seed Field Name Accuracy\n")

    # Build attribute lookup
    schema_attrs = {}
    for s in OBJECT_SCHEMAS:
        sname = _to_snake(s["name"])
        attrs = {a["name"] for a in s.get("attributes", [])}
        attrs.update({"name", "display_name", "description",
                      "parent_type", "parent_uuid", "parent_context",
                      "parent_fq_name", "enabled", "status"})
        for ref in s.get("references", []):
            rs = _to_snake(ref.get("name", ""))
            attrs.add(f"{rs}_uuid")
            attrs.add(f"{rs}_uuids")
        schema_attrs[sname] = attrs
        schema_attrs[s["name"]] = attrs

    mismatches = 0
    for node in ast.walk(setup_tree):
        if not isinstance(node, ast.Call):
            continue
        func_name = None
        if isinstance(node.func, ast.Name):
            func_name = node.func.id
        elif isinstance(node.func, ast.Attribute):
            func_name = node.func.attr
        if func_name != "seed_record":
            continue

        # Extract schema name (arg 3) and data dict (arg 4)
        seed_schema = None
        if len(node.args) >= 4 and isinstance(node.args[3], ast.Constant):
            seed_schema = str(node.args[3].value)

        data_arg = node.args[4] if len(node.args) >= 5 else None
        if data_arg is None:
            for kw in node.keywords:
                if kw.arg == "data":
                    data_arg = kw.value
                    break

        if not seed_schema or not data_arg or not isinstance(data_arg, ast.Dict):
            continue

        valid = schema_attrs.get(_to_snake(seed_schema)) or schema_attrs.get(seed_schema)
        if not valid:
            continue

        for key_node in data_arg.keys:
            if not isinstance(key_node, ast.Constant):
                continue
            fname = str(key_node.value)
            if fname in valid:
                continue
            # Suggest close match
            close = [a for a in valid
                     if a.endswith(fname.split("_")[-1]) or fname.endswith(a.split("_")[-1])]
            base_attrs = valid - {"name", "display_name", "description", "parent_type",
                                   "parent_uuid", "parent_context", "parent_fq_name",
                                   "enabled", "status"}
            if close:
                suite.fail("seed-fields",
                           f"{seed_schema}.{fname} -- not in schema (did you mean '{close[0]}'?)",
                           f"Valid: {', '.join(sorted(base_attrs))}")
            else:
                suite.fail("seed-fields",
                           f"{seed_schema}.{fname} -- not in schema",
                           f"Valid: {', '.join(sorted(base_attrs))}")
            mismatches += 1

    if mismatches == 0:
        suite.ok("seed-fields", f"All seed fields match schema attributes ({len(schema_attrs)//2} schemas)")

    # Also syntax-check __main__.py and ui/server.py
    for extra in ["__main__.py", os.path.join("ui", "server.py")]:
        extra_path = os.path.join(APP_DIR, extra)
        if os.path.exists(extra_path):
            try:
                with open(extra_path) as f:
                    ast.parse(f.read())
                suite.ok("setup", f"{extra} syntax valid")
            except SyntaxError as e:
                suite.fail("setup", f"{extra} SYNTAX ERROR: {e}")


def check_config_js(suite):
    if not suite.json_output:
        print("\n  [7] config.js Validation\n")

    path = os.path.join(APP_DIR, "ui", "config.js")
    if not os.path.exists(path):
        if HAS_VENV:
            suite.fail("config-js", "config.js not found")
        else:
            suite.skip("config-js", "config.js not yet created", "Run ./run.sh first")
        return

    with open(path) as f:
        cjs = f.read()

    if DOMAIN and DOMAIN in cjs:
        suite.ok("config-js", f"Domain: {DOMAIN}")
    elif DOMAIN:
        suite.fail("config-js", f"Domain '{DOMAIN}' not in config.js")

    project = _env("SUPERO_PROJECT")
    if project and project in cjs:
        suite.ok("config-js", f"Project: {project}")
    elif project:
        suite.fail("config-js", f"Project '{project}' not in config.js")

    if "appNamespace" in cjs:
        m = re.search(r'appNamespace:\s*"([^"]*)"', cjs)
        suite.ok("config-js", f"appNamespace: {m.group(1) if m else 'present'}")
    else:
        suite.fail("config-js", "appNamespace MISSING", "Namespace CRUD will 409")

    # Public schemas
    if PUBLIC_SCHEMAS:
        ps_match = re.search(r'publicSchemas:\s*\[([^\]]*)\]', cjs)
        if ps_match:
            cjs_schemas = [s.strip().strip('"').strip("'")
                           for s in ps_match.group(1).split(",") if s.strip()]
            for ps in PUBLIC_SCHEMAS:
                if ps in cjs_schemas:
                    suite.ok("config-js", f"Public schema: {ps}")
                else:
                    suite.fail("config-js", f"Public schema '{ps}' missing from config.js")

    # Multi-tenant
    if IS_MULTI_TENANT:
        if "isMultiTenant: true" in cjs:
            suite.ok("config-js", "isMultiTenant: true")
        else:
            suite.fail("config-js", "isMultiTenant not true", "Signup UI won't render")


def check_app_js(suite):
    if not suite.json_output:
        print("\n  [8] app.js Validation\n")

    path = os.path.join(APP_DIR, "ui", "app.js")
    if not os.path.exists(path):
        suite.fail("app-js", "app.js not found")
        return

    with open(path) as f:
        appjs = f.read()
    size = os.path.getsize(path)
    suite.ok("app-js", f"Size: {size:,}B")

    if "AppShell" in appjs:
        suite.ok("app-js", "Uses AppShell pattern")
    elif "React" in appjs or "createElement" in appjs:
        suite.ok("app-js", "Uses React pattern")
    else:
        suite.skip("app-js", "UI framework not detected", "Check app.js manually")

    if "AppShell.render" in appjs or "render(" in appjs:
        suite.ok("app-js", "render() call present")
    else:
        suite.fail("app-js", "No render() call", "UI won't display")

    if "__SUPERO_CONFIG" in appjs or "SUPERO_CONFIG" in appjs:
        suite.ok("app-js", "Wired to SUPERO_CONFIG (config.js)")
    else:
        suite.skip("app-js", "No SUPERO_CONFIG reference",
                   "App may use window.__SUPERO_CONFIG or inline config pattern")

    # Hardcoded domain check
    if DOMAIN and f'"{DOMAIN}"' in appjs:
        count = appjs.count(f'"{DOMAIN}"')
        if count > 3:
            suite.fail("app-js", f"Domain hardcoded {count} times")
        else:
            suite.ok("app-js", f"Domain references OK ({count})")

    # Tabs/sections
    if "TABS" in appjs or "tabs:" in appjs:
        tabs = len(re.findall(r'(?:label|title)\s*:\s*["\']', appjs))
        if tabs:
            suite.ok("app-js", f"UI tabs defined ({tabs} labels)")
    else:
        suite.skip("app-js", "No TABS config", "May use different UI layout pattern")


def check_supero_ui_js(suite):
    if not suite.json_output:
        print("\n  [9] supero-ui.js (legacy monolith + layered files)\n")

    # LAYERED_UI_V1 — check the layered files first (the new shipping path).
    # Symbols moved during the split: _qualifySchema lives in api/10-schemas.js,
    # SuperoClient in api/11-client.js. Validate they're each present.
    layer_checks = [
        ("ui/web/api/10-schemas.js",    "_qualifySchema",   "Namespace qualifier in api/10-schemas.js"),
        ("ui/web/api/11-client.js",     "SuperoClient",     "SuperoClient class in api/11-client.js"),
        ("ui/web/ui-app/53-shell.js",   "AppShell",         "AppShell in ui-app/53-shell.js"),
        ("ui/web/ui-app/54-nav-widgets.js", "_NavWidget",   "Nav widgets in ui-app/54-nav-widgets.js"),
    ]
    layered_present = all(
        os.path.exists(os.path.join(APP_DIR, p)) for p, _, _ in layer_checks
    )
    if layered_present:
        for relpath, symbol, label in layer_checks:
            full = os.path.join(APP_DIR, relpath)
            try:
                with open(full) as f:
                    content = f.read()
                if symbol in content:
                    suite.ok("ui-js", label)
                else:
                    suite.fail("ui-js", f"{symbol} missing from {relpath}",
                               "Corrupted layered file — re-run ./run.sh")
            except OSError as exc:
                suite.fail("ui-js", f"Could not read {relpath}: {exc}")
    else:
        suite.skip("ui-js", "Layered files not extracted (legacy app?)",
                   "Run ./run.sh to extract ui/web/* files")

    # Legacy supero-ui.js — kept bundled for /supero-ui.js route fallback;
    # check it too so apps that haven't migrated index.html still validate.
    path = os.path.join(APP_DIR, "ui", "supero-ui.js")
    if not os.path.exists(path):
        if HAS_VENV:
            suite.skip("ui-js", "Legacy supero-ui.js not extracted (LAYERED_UI_V1 default)")
        else:
            suite.skip("ui-js", "supero-ui.js not yet downloaded", "Run ./run.sh first")
        return

    with open(path) as f:
        uijs = f.read()
    size = os.path.getsize(path)

    if "_qualifySchema" in uijs:
        suite.ok("ui-js", "Namespace qualifier in legacy supero-ui.js")
    else:
        suite.fail("ui-js", "_qualifySchema MISSING from supero-ui.js",
                   "Old SDK version. Update and re-run.")

    if "SuperoClient" in uijs:
        suite.ok("ui-js", "SuperoClient class in legacy supero-ui.js")
    else:
        suite.fail("ui-js", "SuperoClient missing from supero-ui.js", "Corrupted file")

    if size < 10000:
        suite.fail("ui-js", f"Suspiciously small ({size:,}B)", "Expected ~400KB+")
    else:
        suite.ok("ui-js", f"Size OK ({size:,}B)")


def check_run_sh(suite):
    if not suite.json_output:
        print("\n  [10] run.sh\n")

    path = os.path.join(APP_DIR, "run.sh")
    if not os.path.exists(path):
        suite.fail("run-sh", "run.sh not found")
        return

    with open(path) as f:
        runsh = f.read()

    if "__SUPERO_MIN_VERSION__" in runsh:
        suite.fail("run-sh", "SDK version placeholder not stamped!",
                   "AI service didn't replace __SUPERO_MIN_VERSION__")
    elif "supero==" in runsh:
        m = re.search(r'supero==([0-9.]+)', runsh)
        if m:
            suite.ok("run-sh", f"SDK pinned: supero=={m.group(1)}")
    elif "supero>=" in runsh:
        m = re.search(r'supero>=([0-9.]+)', runsh)
        if m:
            v = m.group(1)
            if v == "1.5.0":
                suite.fail("run-sh", f"SDK stale: supero>={v}", "Rebuild AI service")
            else:
                suite.ok("run-sh", f"SDK minimum: supero>={v}")

    if os.access(path, os.X_OK):
        suite.ok("run-sh", "Executable")
    else:
        suite.fail("run-sh", "Not executable", "chmod +x run.sh")


def check_dockerfile(suite):
    if not suite.json_output:
        print("\n  [11] Dockerfile\n")

    path = os.path.join(APP_DIR, "Dockerfile")
    if not os.path.exists(path):
        if HAS_VENV:
            suite.fail("docker", "Dockerfile not found")
        else:
            suite.skip("docker", "Dockerfile not yet generated", "Run ./run.sh first")
        return

    with open(path) as f:
        df = f.read()

    m = re.search(r'FROM\s+(\S+)', df)
    if m:
        suite.ok("docker", f"Base image: {m.group(1)}")
    else:
        suite.fail("docker", "No FROM instruction")

    if "COPY" in df or "ADD" in df:
        suite.ok("docker", "Has COPY/ADD")
    else:
        suite.fail("docker", "No COPY/ADD")

    if "CMD" in df or "ENTRYPOINT" in df:
        suite.ok("docker", "Has CMD/ENTRYPOINT")
    else:
        suite.fail("docker", "No CMD/ENTRYPOINT")

    if "COPY .env" in df or "ADD .env" in df:
        suite.fail("docker", ".env copied into image!", "Credentials leak risk")
    else:
        suite.ok("docker", ".env not in image (correct)")

    m = re.search(r'EXPOSE\s+(\d+)', df)
    if m:
        suite.ok("docker", f"EXPOSE {m.group(1)}")
    else:
        suite.skip("docker", "No EXPOSE", "Optional")

    # docker-compose
    compose = os.path.join(APP_DIR, "docker-compose.yml")
    if os.path.exists(compose):
        with open(compose) as f:
            if "services:" in f.read():
                suite.ok("docker", "docker-compose.yml valid")
            else:
                suite.fail("docker", "docker-compose.yml missing services:")
    else:
        suite.skip("docker", "No docker-compose.yml", "Optional")


def check_docs(suite):
    if not suite.json_output:
        print("\n  [12] Documentation\n")

    docs = {
        "README.md": (True, [("app_name", cfg.app_name), ("domain", DOMAIN)]),
        "CLAUDE.md": (True, [("supero", "supero"), ("schema", "schema")]),
        "CUSTOMIZATION.md": (False, [("custom", "custom")]),
        ".cursorrules": (False, []),
        ".windsurfrules": (False, []),
    }
    for name, (required, checks) in docs.items():
        path = os.path.join(APP_DIR, name)
        if os.path.exists(path):
            size = os.path.getsize(path)
            if size < 100:
                suite.fail("docs", f"{name} too small ({size}B)")
            else:
                suite.ok("docs", f"{name} ({size:,}B)")
            if checks:
                with open(path) as f:
                    content = f.read().lower()
                for label, term in checks:
                    if term and term.lower() in content:
                        suite.ok("docs", f"{name} mentions {label}")
                    else:
                        suite.skip("docs", f"{name}: no {label}", "Optional content")
        elif required:
            if HAS_VENV:
                suite.fail("docs", f"{name} MISSING")
            else:
                suite.skip("docs", f"{name} not yet generated", "Run ./run.sh first")
        else:
            suite.skip("docs", f"{name} not generated", "Optional")


def check_public_wiring(suite):
    if not suite.json_output:
        print("\n  [13] Public Schema Wiring\n")

    if not PUBLIC_SCHEMAS:
        suite.skip("public-wiring", "Public wiring", "No PUBLIC_SCHEMAS configured")
        return

    # .env -> config.js
    cjs_path = os.path.join(APP_DIR, "ui", "config.js")
    if os.path.exists(cjs_path):
        with open(cjs_path) as f:
            cjs = f.read()
        ps_match = re.search(r'publicSchemas:\s*\[([^\]]*)\]', cjs)
        cjs_schemas = []
        if ps_match:
            cjs_schemas = [s.strip().strip('"').strip("'")
                           for s in ps_match.group(1).split(",") if s.strip()]
        for ps in PUBLIC_SCHEMAS:
            if ps in cjs_schemas:
                suite.ok("public-wiring", f".env -> config.js: '{ps}'")
            else:
                suite.fail("public-wiring", f"'{ps}' in .env but not in config.js",
                           "Re-run ./run.sh --setup-only")

    # config.js -> app.js
    # AppShell auto-renders public schemas from config.js publicSchemas array.
    # app.js may reference them explicitly OR rely on AppShell's auto-render.
    appjs_path = os.path.join(APP_DIR, "ui", "app.js")
    if os.path.exists(appjs_path):
        with open(appjs_path) as f:
            appjs = f.read()
        if ("publicSchemas" in appjs or "BrowseList" in appjs
                or "AppShell" in appjs or "signupMode" in appjs):
            suite.ok("public-wiring", "app.js has AppShell/public rendering")
        else:
            suite.fail("public-wiring", "app.js has no AppShell or public schema references")

        for ps in PUBLIC_SCHEMAS:
            variants = [ps, _to_snake(ps), ps.replace("_", " ").title()]
            if any(v in appjs for v in variants):
                suite.ok("public-wiring", f"app.js has section for '{ps}'")
            else:
                suite.skip("public-wiring", f"No explicit tab for '{ps}'",
                           "AppShell auto-renders from publicSchemas config")


def check_sdk_versions(suite):
    if not suite.json_output:
        print("\n  [14] SDK Versions\n")

    # Pre-flight: just check run.sh has a version pinned
    runsh = os.path.join(APP_DIR, "run.sh")
    if os.path.exists(runsh):
        with open(runsh) as f:
            content = f.read()
        m = re.search(r'supero[=>]=([0-9.]+)', content)
        if m:
            suite.ok("sdk", f"run.sh pins supero {m.group(0)}")
        else:
            suite.skip("sdk", "run.sh SDK version not found", "Check manually")

    # Tenant SDK wheel exists
    for f in os.listdir(APP_DIR):
        if f.startswith("supero_") and f.endswith(".whl"):
            m = re.match(r'supero_[^-]+-([0-9.]+)-', f)
            suite.ok("sdk", f"Tenant wheel: {f}" + (f" (v{m.group(1)})" if m else ""))
            break
    else:
        suite.skip("sdk", "No tenant SDK wheel", "Generated by platform-core")


# ---------------------------------------------------------------
# [17] Tab Schema References — app.js tabs[].schema must match
# a registered schema in schemas.py.
# ---------------------------------------------------------------
#
# Catches the most common LLM generation bug: `tab.schema` values
# that don't match any registered schema name. Typical failures:
#
#   schemas.py:  {"name": "FormDefinition"}   → stored as form_definition
#   app.js:      schema: 'formdefinition'      → 404 at runtime
#
# This check parses every `schema: 'xxx'` occurrence in app.js and
# cross-references it against the ALL_SCHEMAS table. Mismatches fail
# the bundle with a suggestion of the correct name (when we can
# guess it via normalized-name comparison).
#
# Add this function anywhere near check_app_js in test_bundle.py,
# then wire it in main() right after check_workflow_config (or wherever
# check ordering feels natural).

def check_tab_schema_references(suite):
    """[17] Tab Schema References — app.js tabs match schemas.py."""
    if not suite.json_output:
        print("\n  [17] Tab Schema References\n")

    path = os.path.join(APP_DIR, "ui", "app.js")
    if not os.path.exists(path):
        suite.skip("tab-schemas", "Tab schema check",
                   "app.js not found (already reported in [8])")
        return

    if not OBJECT_SCHEMAS:
        suite.skip("tab-schemas", "Tab schema check",
                   "No object schemas in schemas.py")
        return

    with open(path) as f:
        appjs = f.read()

    # ── Build the set of registered schema names in canonical snake_case ──
    #
    # Match the tabs[].schema values against multiple valid forms:
    #   - canonical snake:            "form_definition"
    #   - namespace-qualified:        "your_namespace:form_definition"
    #   - original PascalCase:        "FormDefinition"
    #
    # A tab schema value is valid if it matches ANY of these forms for
    # ANY registered schema.
    registered = []  # [(canonical_snake, original_name), ...]
    for s in OBJECT_SCHEMAS:
        original = s.get("name", "")
        if not original:
            continue
        registered.append((_to_snake(original), original))

    canonical_snake_set = {c for c, _ in registered}
    original_name_set = {o for _, o in registered}

    # ── Parse tabs[].schema values from app.js ──
    #
    # Matches patterns like:
    #   schema: 'form_definition'
    #   schema: "FormDefinition"
    #   schema:'formdefinition'
    # while capturing the line number for error messages.
    schema_refs = []  # [(line_no, value, tab_id_or_None), ...]

    # Split into lines so we can report line numbers
    lines = appjs.splitlines()

    # Track the most recent `id: '...'` so we can associate a `schema:`
    # with its containing tab. Not perfect (nested objects break it) but
    # good enough for the 95% case and only used for error-message hints.
    #
    # Regex shape notes:
    #   - `(?:^|[,{\s])` requires the `schema:` to be at start-of-line
    #     (modulo whitespace) or preceded by a comma/brace. This filters
    #     out matches inside prose strings like "description of schema:".
    #   - We also skip lines whose stripped form starts with `//` or `*`
    #     (common comment markers). This isn't a full JS parser but
    #     catches the realistic false-positive cases.
    recent_id = None
    id_re = re.compile(r"""(?:^|[,{\s])id:\s*['"]([^'"]+)['"]""")
    schema_re = re.compile(r"""(?:^|[,{\s])schema:\s*['"]([^'"]+)['"]""")

    for i, line in enumerate(lines, start=1):
        stripped = line.lstrip()
        # Skip line-comments and block-comment continuation lines.
        # (Block comments that span multiple lines and include the word
        # "schema:" inside are rare enough we don't handle them.)
        if stripped.startswith("//") or stripped.startswith("*"):
            continue

        id_match = id_re.search(line)
        if id_match:
            recent_id = id_match.group(1)

        schema_match = schema_re.search(line)
        if schema_match:
            schema_refs.append((i, schema_match.group(1), recent_id))

    if not schema_refs:
        suite.skip("tab-schemas", "Tab schema check",
                   "No schema: '...' declarations found in app.js")
        return

    suite.ok("tab-schemas",
             f"Found {len(schema_refs)} schema reference(s) in app.js")

    # ── Validate each reference ──
    def _strip_namespace(value):
        """`ns:schema` → `schema`; `schema` → `schema`."""
        return value.split(":", 1)[1] if ":" in value else value

    def _suggest_correction(bad_value):
        """Given a broken schema value, find the best match in registered.

        Strategy: normalize the bad value the same way we normalize
        registered names, then look for an exact match. If that fails,
        try substring matching. Returns the suggested canonical name
        or None.
        """
        bad_bare = _strip_namespace(bad_value).lower()
        bad_normalized = _to_snake(_strip_namespace(bad_value))

        # Exact normalized match (handles PascalCase passed as-is)
        if bad_normalized in canonical_snake_set:
            return bad_normalized

        # "formdefinition" has no underscores → try matching against
        # registered names with underscores stripped. If unique, that's
        # almost certainly what the LLM meant.
        stripped_registered = {
            canonical.replace("_", ""): canonical
            for canonical, _ in registered
        }
        if bad_bare in stripped_registered:
            return stripped_registered[bad_bare]

        # Substring fallback: does any registered canonical CONTAIN the
        # bad value (or vice versa)? Only suggest if unambiguous.
        substring_matches = [
            canonical for canonical in canonical_snake_set
            if bad_bare in canonical.replace("_", "")
               or canonical.replace("_", "") in bad_bare
        ]
        if len(substring_matches) == 1:
            return substring_matches[0]

        return None

    failures = 0
    orphan_refs = []  # references to schemas we couldn't correct

    for line_no, value, tab_id in schema_refs:
        bare = _strip_namespace(value)

        # Valid if any of these match
        is_valid = (
            bare in canonical_snake_set       # already canonical snake
            or bare in original_name_set      # original PascalCase / unchanged
            or _to_snake(bare) in canonical_snake_set  # PascalCase being fine
        )

        if is_valid:
            tab_hint = f" (tab '{tab_id}')" if tab_id else ""
            suite.ok("tab-schemas",
                     f"line {line_no}{tab_hint}: schema '{value}' ✓")
            continue

        # Invalid — try to suggest a fix
        failures += 1
        suggestion = _suggest_correction(value)
        tab_hint = f" (tab '{tab_id}')" if tab_id else ""

        if suggestion:
            msg = (
                f"line {line_no}{tab_hint}: schema '{value}' does NOT match "
                f"any registered schema. Did you mean '{suggestion}'? "
                f"Fix: edit ui/app.js line {line_no} to use "
                f"schema: '{suggestion}'"
            )
        else:
            msg = (
                f"line {line_no}{tab_hint}: schema '{value}' does NOT match "
                f"any registered schema, and no close match found. "
                f"Registered: {', '.join(sorted(canonical_snake_set)[:8])}"
                + ("..." if len(canonical_snake_set) > 8 else "")
            )
            orphan_refs.append(value)
        suite.fail("tab-schemas", f"Invalid schema reference '{value}'", msg)

    # ── Summary note about orphans (registered-but-unreferenced schemas) ──
    #
    # Collect the set of bare schema names actually referenced by tabs.
    # Any object schema not in that set is "orphaned" from the UI —
    # often fine (backend-only schemas, join tables), so we SKIP
    # rather than fail. Just informational.
    referenced_bare = set()
    for _, value, _ in schema_refs:
        bare = _strip_namespace(value)
        if bare in canonical_snake_set:
            referenced_bare.add(bare)
        elif _to_snake(bare) in canonical_snake_set:
            referenced_bare.add(_to_snake(bare))

    orphaned = canonical_snake_set - referenced_bare
    if orphaned:
        suite.skip(
            "tab-schemas",
            f"{len(orphaned)} schema(s) not referenced by any tab",
            f"Orphans (may be intentional): "
            f"{', '.join(sorted(orphaned)[:5])}"
            + ("..." if len(orphaned) > 5 else "")
        )

    if failures == 0:
        suite.ok("tab-schemas",
                 f"All {len(schema_refs)} schema reference(s) valid")


def check_workflow_config(suite):
    """[16] Workflow Config — EVENT_BINDINGS ↔ WORKFLOW_DEFINITIONS."""
    if not suite.json_output:
        print("\n  [16] Workflow Config\n")

    setup_path = os.path.join(APP_DIR, "setup.py")
    if not os.path.exists(setup_path):
        suite.skip("workflow-config", "Workflow config check", "No setup.py")
        return

    with open(setup_path) as f:
        setup_src = f.read()

    try:
        setup_tree = ast.parse(setup_src)
    except SyntaxError:
        suite.skip("workflow-config", "Workflow config check",
                   "setup.py has syntax error (already reported)")
        return

    def _extract_literal(tree, var_name):
        for node in tree.body:
            if (isinstance(node, ast.Assign)
                    and len(node.targets) == 1
                    and isinstance(node.targets[0], ast.Name)
                    and node.targets[0].id == var_name):
                try:
                    return ast.literal_eval(node.value)
                except (ValueError, SyntaxError):
                    return None
        return None

    wf_defs = _extract_literal(setup_tree, "WORKFLOW_DEFINITIONS") or []
    bindings = _extract_literal(setup_tree, "EVENT_BINDINGS") or []

    if not wf_defs and not bindings:
        suite.skip("workflow-config", "Workflow config check",
                   "No workflows (OK if app has no workflow features)")
        return

    # Build workflow_id → input_schema lookup
    workflow_ids = set()
    wf_input_schemas = {}
    wf_required_inputs = {}
    for wf in wf_defs:
        if not isinstance(wf, dict):
            continue
        wid = wf.get("workflow_id")
        if not wid:
            continue
        workflow_ids.add(wid)
        schema = wf.get("input_schema") or {}
        if isinstance(schema, dict):
            wf_input_schemas[wid] = set(schema.keys())
            wf_required_inputs[wid] = {
                k for k, v in schema.items()
                if isinstance(v, dict) and v.get("required")
            }

    # Schema names from ALL_SCHEMAS (loaded at module top)
    schema_names_all = {s.get("name") for s in ALL_SCHEMAS}
    schema_names_snake = {_to_snake(s.get("name", "")) for s in ALL_SCHEMAS}
    schema_names = schema_names_all | schema_names_snake

    # Allowed singular suffixes (don't false-positive on plural heuristic)
    _singular_ok = ("ss", "us", "is", "os", "ics", "news")

    def _is_probably_plural(schema_part):
        return (len(schema_part) > 3
                and schema_part.endswith("s")
                and not schema_part.endswith(_singular_ok))

    import re as _re
    def _validate_event(event):
        """Return (error_msg, schema_name_or_None). None error = valid."""
        if not isinstance(event, str) or not event.startswith("@"):
            return ("event must start with '@'", None)
        if event == "@signup":
            return (None, None)
        m = _re.match(r"^@([a-z]+):([a-zA-Z][a-zA-Z0-9_:]*)$", event)
        if not m:
            return ("event must be '@<verb>:<schema>'", None)
        verb, schema_part = m.group(1), m.group(2)
        if verb not in ("create", "update", "delete"):
            return ("unknown verb '{}' (use create/update/delete)".format(verb), None)
        if ":" in schema_part:
            return ("schema must be UNQUALIFIED (got '{}')".format(schema_part), None)
        if any(c.isupper() for c in schema_part):
            return ("schema must be snake_case (got '{}')".format(schema_part),
                    schema_part)
        if _is_probably_plural(schema_part):
            return ("schema name looks plural ('{}')".format(schema_part),
                    schema_part)
        return (None, schema_part)

    def _validate_path(path):
        if not isinstance(path, str):
            return "not a string"
        if "{{" in path or "}}" in path:
            return "contains '{{}}' templating — use plain dotted path"
        if path.startswith("$"):
            return "starts with '$' (JSONPath) — use plain dotted path"
        if path.startswith(("record.", "payload.", "data.")):
            return "redundant prefix '{}' — CRUD record IS the payload".format(
                path.split(".")[0])
        if not _re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)*$",
                         path):
            return "doesn't look like a valid dotted path"
        return None

    # ── Summary counts ──────────────────────────────────────────────
    if wf_defs:
        suite.ok("workflow-config",
                 "Found {} WORKFLOW_DEFINITIONS, {} EVENT_BINDINGS".format(
                     len(wf_defs), len(bindings)))

    # ── Check 1: bindings well-formed ───────────────────────────────
    bad_events_seen = set()
    seen_events = set()
    for i, b in enumerate(bindings):
        ctx = "EVENT_BINDINGS[{}]".format(i)
        if not isinstance(b, dict):
            suite.fail("workflow-config", "{} not a dict".format(ctx))
            continue
        event = b.get("event")
        wf_id = b.get("workflow_id")
        input_map = b.get("input_map") or {}

        if not event:
            suite.fail("workflow-config", "{} missing 'event'".format(ctx))
            continue
        if not wf_id:
            suite.fail("workflow-config",
                       "{} (event={!r}) missing 'workflow_id'".format(ctx, event))
            continue

        ctx_e = "EVENT_BINDINGS[{!r}]".format(event)

        # Check 4+5: event format
        err, schema_part = _validate_event(event)
        if err:
            suite.fail("workflow-config", "{} {}".format(ctx_e, err))
            bad_events_seen.add(event)
        else:
            # Check 6: schema exists
            if schema_part and schema_part not in schema_names:
                suite.fail("workflow-config",
                           "{} schema '{}' not in ALL_SCHEMAS".format(
                               ctx_e, schema_part),
                           "Valid: " + ", ".join(sorted(schema_names_snake)[:6]))
            else:
                suite.ok("workflow-config",
                         "{} event format + schema OK".format(ctx_e))

        # Duplicate events
        if event in seen_events:
            suite.fail("workflow-config",
                       "{} duplicate event — only first fires".format(ctx_e))
        seen_events.add(event)

        # Check 3: workflow_id exists
        if wf_id not in workflow_ids:
            suite.fail("workflow-config",
                       "{} workflow_id={!r} has no matching definition".format(
                           ctx_e, wf_id),
                       "Available: " + ", ".join(sorted(workflow_ids)) if workflow_ids
                       else "No WORKFLOW_DEFINITIONS found")
        else:
            # Check 7: input_map keys
            if isinstance(input_map, dict) and wf_id in wf_input_schemas:
                expected = wf_input_schemas[wf_id]
                if expected:
                    unknown = set(input_map.keys()) - expected
                    if unknown:
                        suite.fail("workflow-config",
                                   "{} input_map keys not in workflow input_schema: {}".format(
                                       ctx_e, sorted(unknown)),
                                   "These will be SILENTLY IGNORED. "
                                   "Expected: " + ", ".join(sorted(expected)))
                    missing_req = wf_required_inputs.get(wf_id, set()) - set(input_map.keys())
                    if missing_req:
                        suite.fail("workflow-config",
                                   "{} input_map missing required keys: {}".format(
                                       ctx_e, sorted(missing_req)))

        # Check 8: input_map values are plain paths
        if isinstance(input_map, dict):
            for k, v in input_map.items():
                perr = _validate_path(v)
                if perr:
                    suite.fail("workflow-config",
                               "{} input_map[{!r}]={!r}: {}".format(
                                   ctx_e, k, v, perr))

    # ── Check 9: call order ─────────────────────────────────────────
    if "ensure_event_bindings" in setup_src:
        if "ensure_workflows" not in setup_src:
            suite.fail("workflow-config",
                       "ensure_event_bindings() called without ensure_workflows()",
                       "Register workflow definitions FIRST.")
        else:
            wf_pos = setup_src.find("ensure_workflows(")
            eb_pos = setup_src.find("ensure_event_bindings(")
            if wf_pos > 0 and eb_pos > 0 and eb_pos < wf_pos:
                suite.fail("workflow-config",
                           "ensure_event_bindings() called BEFORE ensure_workflows()",
                           "Bindings reference workflow_ids — swap the order.")
            else:
                suite.ok("workflow-config",
                         "ensure_workflows → ensure_event_bindings order correct")

    # ── Check 10: past-tense workflows without bindings ──────────────
    bound_wf_ids = {b.get("workflow_id") for b in bindings if isinstance(b, dict)}
    def _past_tense(name):
        if not name or "_" not in name:
            return False
        last = name.rsplit("_", 1)[-1]
        return (last.endswith("ed")
                or last in ("completed", "failed", "processed",
                            "received", "sent", "raised"))

    past_tense_unbound = [
        wf.get("workflow_id") for wf in wf_defs
        if isinstance(wf, dict)
        and wf.get("workflow_id")
        and _past_tense(wf["workflow_id"])
        and wf["workflow_id"] not in bound_wf_ids
    ]
    if past_tense_unbound:
        suite.fail("workflow-config",
                   "Past-tense workflows without EVENT_BINDING: {}".format(
                       past_tense_unbound),
                   "These names imply auto-triggers. Add bindings or confirm "
                   "they are admin-only (UI button via WORKFLOW_MAP).")

    # ── Final state ─────────────────────────────────────────────────
    if not bindings and wf_defs:
        # If we already warned about past-tense, don't double-warn
        if not past_tense_unbound:
            suite.skip("workflow-config",
                       "No EVENT_BINDINGS",
                       "All workflows admin-only (UI button only)")


def check_post_install(suite, check_backend=False):
    if not suite.json_output:
        print("\n  [15] Post-Install\n")

    venv = os.path.join(APP_DIR, ".venv")
    if not os.path.exists(venv):
        suite.skip("post-install", "Post-install checks",
                   "No .venv -- run ./run.sh first")
        return

    suite.ok("post-install", ".venv exists (run.sh executed)")

    # SDK version check — run the venv's python to get installed version
    venv_python = os.path.join(venv, "bin", "python3")
    if not os.path.exists(venv_python):
        venv_python = os.path.join(venv, "bin", "python")
    if os.path.exists(venv_python):
        import subprocess
        try:
            # Use a clean command that suppresses import side-effects
            result = subprocess.run(
                [venv_python, "-c",
                 "import importlib; m = importlib.import_module('supero'); print('__VER__' + m.__version__)"],
                capture_output=True, text=True, timeout=10,
                env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"})
            if result.returncode == 0:
                # Extract version from tagged line (ignores debug output)
                v = None
                for line in result.stdout.splitlines():
                    if line.startswith("__VER__"):
                        v = line[7:].strip()
                        break
                if v and re.match(r'^\d+\.\d+\.\d+', v):
                    suite.ok("post-install", f"Base SDK installed: v{v}")
                    runsh = os.path.join(APP_DIR, "run.sh")
                    if os.path.exists(runsh):
                        with open(runsh) as f:
                            rs = f.read()
                        m = re.search(r'supero[=>]=([0-9.]+)', rs)
                        if m:
                            pinned = m.group(1)
                            if v == pinned:
                                suite.ok("post-install", f"SDK version matches run.sh ({v})")
                            else:
                                # Compare versions: installed vs pinned
                                iv = tuple(int(x) for x in v.split(".")[:3])
                                pv = tuple(int(x) for x in pinned.split(".")[:3])
                                if iv >= pv:
                                    suite.ok("post-install",
                                             f"SDK v{v} >= pinned v{pinned} (OK)")
                                else:
                                    suite.fail("post-install",
                                               f"SDK outdated: installed={v}, run.sh={pinned}",
                                               f"Run: source .venv/bin/activate && pip install supero=={pinned}")
                else:
                    suite.skip("post-install", "SDK version unreadable",
                               f"Got: {result.stdout.strip()[:60]}")
            elif "No module named" in result.stderr:
                suite.fail("post-install", "Base SDK not installed in .venv",
                           "Run ./run.sh to install dependencies")
            else:
                suite.skip("post-install", "SDK version check",
                           f"Could not query .venv python: {result.stderr.strip()[:80]}")
        except Exception as e:
            suite.skip("post-install", "SDK version check", str(e)[:80])
    else:
        suite.skip("post-install", "SDK version check", ".venv/bin/python3 not found")

    if API_KEY:
        suite.ok("post-install", "API key present (post-bootstrap)")
    else:
        suite.fail("post-install", "API key missing after run.sh",
                   "bootstrap() should have fetched an API key")

    # config.js correct after setup
    cjs = os.path.join(APP_DIR, "ui", "config.js")
    if os.path.exists(cjs):
        with open(cjs) as f:
            content = f.read()
        if PROJECT and PROJECT in content:
            suite.ok("post-install", f"config.js project: {PROJECT}")
        elif PROJECT:
            suite.fail("post-install", f"config.js missing project '{PROJECT}'")
        # isMultiTenant already checked in config-js section

    # .supero-run.log
    log = os.path.join(APP_DIR, ".supero-run.log")
    if os.path.exists(log):
        suite.ok("post-install", ".supero-run.log exists")
    else:
        suite.skip("post-install", "No .supero-run.log", "Setup may not have completed")

    # Backend record verification (optional -- needs server running)
    if not check_backend:
        suite.skip("post-install", "Backend record check",
                   "Use --post-install to verify records in DB")
        return

    if not API_KEY:
        suite.skip("post-install", "Backend check", "No API key")
        return

    _port = _env("PORT", _env("UI_PORT", "5648"))
    server_url = f"http://localhost:{_port}"

    try:
        import requests
        import urllib3
        urllib3.disable_warnings()
    except ImportError:
        suite.skip("post-install", "Backend check", "requests not installed (run inside .venv)")
        return

    try:
        r = requests.get(f"{server_url}/health", verify=False, timeout=5)
        if r.status_code != 200:
            suite.skip("post-install", "Backend check", f"Server not healthy ({r.status_code})")
            return
    except Exception:
        suite.skip("post-install", "Backend check",
                   f"Server not reachable at {server_url}")
        return

    suite.ok("post-install", f"Server reachable at {server_url}")

    session = requests.Session()
    session.verify = False
    session.headers.update({"X-API-Key": API_KEY, "Content-Type": "application/json"})

    def _qualify(sname):
        if ":" in sname:
            return sname
        return f"{SUPERO_APP_NAMESPACE}:{sname}"

    for s in OBJECT_SCHEMAS:
        sname = _to_snake(s["name"])
        qualified = _qualify(sname)
        display = s.get("display_name", s["name"])
        try:
            r = session.get(
                f"{server_url}/api/v1/crud/{DOMAIN}/{qualified}", timeout=10)
            if r.status_code == 200:
                results = r.json().get("results", [])
                if results:
                    suite.ok("post-install", f"{display}: {len(results)} records")
                elif sname in PUBLIC_SCHEMAS or s["name"] in PUBLIC_SCHEMAS:
                    suite.fail("post-install", f"{display}: EMPTY (public schema!)",
                               "Landing page will be empty")
                else:
                    suite.skip("post-install", f"{display}: no records yet",
                               "Run ./run.sh to seed data")
            elif r.status_code == 409:
                suite.fail("post-install", f"{display}: 409 namespace collision!",
                           f"Bare name ambiguous. Check _qualifySchema in supero-ui.js")
            else:
                suite.fail("post-install", f"{display}: HTTP {r.status_code}")
        except Exception as e:
            suite.fail("post-install", f"{display}: {e}")


# ===============================================================
# MAIN
# ===============================================================


# SUPERO_BILLING_PLUMBING_V1
def check_billing_wiring(suite):
    """[18] Billing Wiring — stripe_checkout service must be plumbed.

    Catches the three common MiniShop-class failure modes:

        (a) stripe_checkout is in config.services but no tab with
            schema='billing_invoice' or billingRole:'invoice' exists,
            AND no EVENT_BINDINGS override maps to a library billing
            workflow. The Pay with Stripe UI will never render.

        (b) WORKFLOW_DEFINITIONS redefines a library-provided billing
            workflow (billing_invoice_created, billing_payment_received)
            or a common PRD alias (order_created, checkout_started,
            payment_success, payment_failed). These must be bound via
            EVENT_BINDINGS, not redefined.

        (c) A tab has billingRole:'invoice' but the referenced schema
            lacks required fields (total_amount, customer_email,
            customer_name). The library workflow input_map can't
            resolve.

    Authoritative reference: docs/8.billing.md (renamed-schema contract).
    """
    if not suite.json_output:
        print("\n  [18] Billing Wiring\n")

    # ── Load source files ──
    config_path = os.path.join(APP_DIR, "config.py")
    app_js_path = os.path.join(APP_DIR, "ui", "app.js")
    setup_path  = os.path.join(APP_DIR, "setup.py")
    schemas_path = os.path.join(APP_DIR, "schemas.py")

    def _read(p):
        if not os.path.exists(p):
            return ""
        with open(p) as f:
            return f.read()

    config_py  = _read(config_path)
    app_js     = _read(app_js_path)
    setup_py   = _read(setup_path)
    schemas_py = _read(schemas_path)

    # ── Fast exit: no billing/stripe involvement at all ──
    stripe_in_config = ("stripe_checkout" in config_py
                        or "'stripe_checkout'" in config_py
                        or '"stripe_checkout"' in config_py)
    billing_in_config = ("'billing'" in config_py
                         or '"billing"' in config_py)

    if not (stripe_in_config or billing_in_config):
        suite.skip("billing-wiring", "Billing wiring check",
                   "No billing/stripe_checkout service — N/A")
        return

    # ──────────────────────────────────────────────────────────────
    # Check (a): stripe_checkout listed but nothing wires it
    # ──────────────────────────────────────────────────────────────
    if stripe_in_config:
        has_invoice_schema = ("schema: 'billing_invoice'" in app_js
                              or 'schema: "billing_invoice"' in app_js)
        has_billing_role   = ("billingRole: 'invoice'" in app_js
                              or 'billingRole: "invoice"' in app_js)
        has_library_binding = ("billing_invoice_created" in setup_py
                               or "billing_payment_received" in setup_py)

        if not (has_invoice_schema or has_billing_role or has_library_binding):
            suite.fail(
                "billing-wiring",
                "stripe_checkout has no billing path",
                "config.services includes 'stripe_checkout' but app.js has no\n"
                "tab with schema='billing_invoice' or billingRole:'invoice',\n"
                "and setup.py has no EVENT_BINDINGS pointing at\n"
                "billing_invoice_created or billing_payment_received.\n"
                "\n"
                "Fix: either (1) add billingRole:'invoice' to your order/invoice\n"
                "tab, OR (2) rename a schema to 'billing_invoice'. Then add\n"
                "an EVENT_BINDINGS entry mapping @create:<yourschema> →\n"
                "billing_invoice_created. See docs/8.billing.md §'The\n"
                "renamed-schema contract'."
            )
        else:
            paths = []
            if has_invoice_schema:   paths.append("billing_invoice schema")
            if has_billing_role:     paths.append("billingRole:'invoice' tab")
            if has_library_binding:  paths.append("library workflow binding")
            suite.ok("billing-wiring",
                     "stripe_checkout wired via: " + ", ".join(paths))

    # ──────────────────────────────────────────────────────────────
    # Check (b): app redefines library-provided billing workflows
    # ──────────────────────────────────────────────────────────────
    LIBRARY_WF_IDS = (
        "billing_invoice_created",
        "billing_payment_received",
        # PRD aliases the LLM commonly mistakenly redefines:
        "order_created", "checkout_started", "checkout_completed",
        "payment_success", "payment_failed",
        "invoice_created", "payment_received",
    )

    # Parse WORKFLOW_DEFINITIONS via AST, same pattern as check_workflow_config
    wf_defs = []
    try:
        import ast as _ast
        tree = _ast.parse(setup_py)
        for node in tree.body:
            if (isinstance(node, _ast.Assign)
                    and len(node.targets) == 1
                    and isinstance(node.targets[0], _ast.Name)
                    and node.targets[0].id == "WORKFLOW_DEFINITIONS"):
                try:
                    wf_defs = _ast.literal_eval(node.value)
                except (ValueError, SyntaxError):
                    wf_defs = []
                break
    except SyntaxError:
        wf_defs = []

    redefined = []
    for wf in wf_defs:
        if isinstance(wf, dict):
            wfid = wf.get("workflow_id")
            if wfid in LIBRARY_WF_IDS and wf.get("steps"):
                redefined.append(wfid)

    if redefined:
        suite.fail(
            "billing-wiring",
            f"WORKFLOW_DEFINITIONS redefines library workflows: {redefined}",
            "These workflows are provided by the library when 'billing' is in\n"
            "config.services. Redefining them causes duplicate registrations\n"
            "and maintenance drift. Remove them and use EVENT_BINDINGS to\n"
            "bind your schemas to 'billing_invoice_created' and\n"
            "'billing_payment_received'. See docs/8.billing.md §'PRD\n"
            "terminology → library workflow lookup'."
        )
    elif wf_defs:
        suite.ok("billing-wiring",
                 f"No library-workflow redefinitions in {len(wf_defs)} WORKFLOW_DEFINITIONS")

    # ──────────────────────────────────────────────────────────────
    # Check (c): billingRole:'invoice' without required schema fields
    # ──────────────────────────────────────────────────────────────
    billing_role_pat = re.compile(
        r"schema:\s*['\"]([a-z_]+)['\"][^{}]*?billingRole:\s*['\"]invoice['\"]",
        re.DOTALL
    )
    # Also match the reverse order (billingRole before schema)
    billing_role_pat_rev = re.compile(
        r"billingRole:\s*['\"]invoice['\"][^{}]*?schema:\s*['\"]([a-z_]+)['\"]",
        re.DOTALL
    )

    invoice_role_schemas = set()
    for m in billing_role_pat.finditer(app_js):
        invoice_role_schemas.add(m.group(1))
    for m in billing_role_pat_rev.finditer(app_js):
        invoice_role_schemas.add(m.group(1))

    for sname in invoice_role_schemas:
        # Required fields for the library workflow input_map per
        # 8.billing.md renamed-schema contract
        required = ("total_amount", "customer_email", "customer_name")
        combined = schemas_py + "\n" + app_js
        # We check combined because attrs can also be declared inline
        # in app.js tabs.
        missing = [f for f in required if f not in combined]
        if missing:
            suite.fail(
                "billing-wiring",
                f"billingRole:'invoice' schema '{sname}' missing fields: {missing}",
                f"The InvoicePayPanel and library workflow input_map depend\n"
                f"on {list(required)}. Add the missing fields to the schema\n"
                f"definition in schemas.py. See docs/8.billing.md §'The\n"
                f"renamed-schema contract' step 2."
            )
        else:
            suite.ok("billing-wiring",
                     f"billingRole:'invoice' schema '{sname}' has required fields")

    if not invoice_role_schemas and billing_in_config:
        # billing service is on but no invoice role tab — only warn if
        # there's no billing_invoice tab either (covered by check a).
        pass

def main():
    parser = argparse.ArgumentParser(
        description="Pre-flight validation for Supero apps",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--bail", action="store_true", help="Stop on first failure")
    parser.add_argument("--json", action="store_true", help="JSON output for CI")
    parser.add_argument("--post-install", action="store_true",
                        help="Include backend record verification (needs server running)")
    args = parser.parse_args()

    if not DOMAIN:
        print("  x SUPERO_DOMAIN not set -- check .env")
        sys.exit(1)

    suite = TestSuite(bail=args.bail, json_output=args.json)

    _is_pre_install = not HAS_VENV

    if not args.json:
        print(f"\n{'='*60}")
        print(f"  Bundle Validation -- {cfg.app_name}")
        print(f"  Domain: {DOMAIN} | Project: {PROJECT}")
        print(f"  Schemas: {len(OBJECT_SCHEMAS)} objects, {len(ENUM_SCHEMAS)} enums")
        print(f"  Public: {', '.join(PUBLIC_SCHEMAS) or '(none)'}")
        if _is_pre_install:
            print(f"\n  Mode: PRE-FLIGHT (no .venv found)")
            print(f"  Only validating AI-generated files.")
            print(f"  Files created by ./run.sh will be skipped.")
        else:
            print(f"\n  Mode: POST-INSTALL (.venv found)")
        print(f"{'='*60}")

    check_required_files(suite)
    check_env(suite)
    check_schemas(suite)
    check_tab_schema_references(suite)
    check_config(suite)
    check_setup_py(suite)
    check_config_js(suite)
    check_app_js(suite)
    check_supero_ui_js(suite)
    check_run_sh(suite)
    check_dockerfile(suite)
    check_docs(suite)
    check_public_wiring(suite)
    check_sdk_versions(suite)
    check_workflow_config(suite)
    check_billing_wiring(suite)
    check_post_install(suite, check_backend=args.post_install)

    all_passed = suite.print_summary()

    if not args.json and _is_pre_install:
        print(f"\n  Next steps:")
        print(f"    1. ./run.sh                    Install SDK, bootstrap, seed data, start server")
        print(f"    2. ./run.sh --verify            Post-install validation (all checks)")
        print(f"    3. ./run.sh --e2e               Runtime e2e tests (server must be running)")
        print()

    sys.exit(0 if all_passed else 1)


if __name__ == "__main__":
    main()
